package com.example.taxcalculator.models;

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import com.example.taxcalculator.utils.TaxManager;
import java.io.Serializable;

/**
 * Represents a product item in the application.
 * This class serves as the data model for products, stored in the Room database.
 * It contains details like name, brand, price, tax category, and barcode.
 */
@Entity(tableName = "product_table")
public class ProductItem implements Serializable {

    /**
     * Unique identifier for the product, auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /**
     * The name of the product.
     */
    private String name;

    /**
     * The brand name of the product.
     */
    private String brand;

    /**
     * The Maximum Retail Price (MRP) of the product.
     */
    private double price;

    /**
     * The identifier for the tax category associated with this product.
     * Used to lookup the dynamic tax rate.
     */
    private String taxCategory;

    /**
     * The barcode string associated with the product.
     */
    private String barcode;

    /**
     * Constructs a new ProductItem.
     *
     * @param name        The name of the product.
     * @param brand       The brand of the product.
     * @param price       The price of the product.
     * @param taxCategory The tax category ID for the product.
     * @param barcode     The scanned barcode of the product.
     */
    public ProductItem(String name, String brand, double price, String taxCategory, String barcode) {
        this.name = name;
        this.brand = brand;
        this.price = price;
        this.taxCategory = taxCategory;
        this.barcode = barcode;
    }

    /**
     * Gets the name of the product.
     * @return The product name.
     */
    public String getName() { return name; }

    /**
     * Gets the brand of the product.
     * @return The brand name.
     */
    public String getBrand() { return brand; }

    /**
     * Gets the price of the product.
     * @return The product price (MRP).
     */
    public double getPrice() { return price; }

    /**
     * Gets the barcode of the product.
     * @return The barcode string.
     */
    public String getBarcode() { return barcode; }

    /**
     * Gets the tax category ID of the product.
     * @return The tax category ID.
     */
    public String getTaxCategory() { return taxCategory; }

    /**
     * Retrieves the current tax rate for the product's category.
     * Queries the TaxManager for the rate associated with the stored category ID.
     *
     * @return The tax rate as a percentage (e.g., 18.0).
     */
    public double getTaxRate() {
        return TaxManager.getInstance().getRate(taxCategory);
    }

    /**
     * Calculates the tax amount included in the price.
     * Formula: (Price * TaxRate) / (100 + TaxRate)
     *
     * @return The calculated tax amount.
     */
    public double getTaxAmount() {
        return (price * getTaxRate()) / (100 + getTaxRate());
    }

    /**
     * Calculates the net price of the product before tax.
     * Formula: Price - TaxAmount
     *
     * @return The net price.
     */
    public double getNetPrice() {
        return price - getTaxAmount();
    }

    /**
     * Returns the total price of the product (same as MRP).
     * @return The total price.
     */
    public double getTotalPrice() { return price; }
}