package com.example.taxcalculator.models;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.taxcalculator.utils.TaxManager;

import java.io.Serializable;

/**
 * Represents a product item in the application.
 * This class serves as the data model for products, stored in the Room database.
 * It contains details like name, brand, price, tax category, and barcode.
 */
@Entity(tableName = "product_table")
public class ProductItem implements Serializable {

    /**
     * Unique identifier for the product, auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    private String name;
    private String brand;

    /** The Maximum Retail Price (MRP) — tax inclusive. */
    private double price;

    /** The identifier for the tax category (used to look up rate in TaxManager). */
    private String taxCategory;

    private String barcode;

    public ProductItem(String name, String brand, double price,
                       String taxCategory, String barcode) {
        this.name        = name;
        this.brand       = brand;
        this.price       = price;
        this.taxCategory = taxCategory;
        this.barcode     = barcode;
    }

    // ─── Getters ────────────────────────────────────────────────────────────

    public String getName()        { return name; }
    public String getBrand()       { return brand; }
    public double getPrice()       { return price; }
    public String getBarcode()     { return barcode; }
    public String getTaxCategory() { return taxCategory; }

    // ─── Tax Calculations ───────────────────────────────────────────────────

    /**
     * Retrieves the applicable GST rate for this product's category.
     * Delegates to TaxManager singleton.
     *
     * @return Tax rate as a percentage (e.g. 18.0 for 18%).
     */
    public double getTaxRate() {
        return TaxManager.getInstance().getRate(taxCategory);
    }

    /**
     * Calculates the total GST amount embedded in the MRP.
     * Formula: (MRP × Rate) / (100 + Rate)
     * This is the "tax-inclusive" reverse calculation — correct for Indian MRP pricing.
     *
     * Example: MRP ₹118, Rate 18% → Tax = (118 × 18) / (100 + 18) = ₹18.00
     *
     * @return Total GST amount (CGST + SGST combined).
     */
    public double getTaxAmount() {
        return (price * getTaxRate()) / (100 + getTaxRate());
    }

    /**
     * Calculates the net price before GST (the actual cost of the product).
     * Formula: MRP − TaxAmount
     *
     * @return Net price excluding GST.
     */
    public double getNetPrice() {
        return price - getTaxAmount();
    }

    /**
     * Returns the MRP (same as the stored price, tax-inclusive).
     *
     * @return Total price / MRP.
     */
    public double getTotalPrice() {
        return price;
    }

    // ─── CGST / SGST Split ──────────────────────────────────────────────────

    /**
     * Calculates the Central GST (CGST) component.
     *
     * In India, for intrastate supply, the total GST is always split equally:
     *   Total GST = CGST + SGST (50% each)
     * For interstate supply it would be IGST only — but since this app targets
     * retail consumers buying at MRP (intrastate), CGST/SGST split is the norm.
     *
     * Formula: TaxAmount / 2
     *
     * Example: 18% GST on ₹118 MRP → Total tax ₹18 → CGST = ₹9, SGST = ₹9
     *
     * @return CGST amount (half of total tax amount).
     */
    public double getCGST() {
        return getTaxAmount() / 2;
    }

    /**
     * Calculates the State GST (SGST) component.
     * Always equal to CGST for intrastate retail transactions.
     *
     * @return SGST amount (half of total tax amount).
     */
    public double getSGST() {
        return getTaxAmount() / 2;
    }

    /**
     * Returns the CGST rate as a percentage (half of total GST rate).
     * Useful for displaying "CGST @ 9%" on the product card.
     *
     * @return CGST rate (e.g. 9.0 for an 18% GST product).
     */
    public double getCGSTRate() {
        return getTaxRate() / 2;
    }

    /**
     * Returns the SGST rate as a percentage (half of total GST rate).
     *
     * @return SGST rate (e.g. 9.0 for an 18% GST product).
     */
    public double getSGSTRate() {
        return getTaxRate() / 2;
    }
}